Improve error message for missing 'llvm_var' statements in spec.
Old error:

    $ saw verify.saw
    Loading module Cryptol
    Loading file "verify.saw"
    Successfully verified @decode_inverts_encode
    Simulation error: src/Verifier/LLVM/Simulator/Internals.hs:259:25-30: Assertion failed

    saw: src/Verifier/LLVM/Simulator/Internals.hs:259:25-30: Assertion failed

New error:

    $ saw verify.saw
    Loading module Cryptol
    Loading file "verify.saw"
    Successfully verified @decode_inverts_encode
    Error: length formals == 7 != length args == 6 in Symbol "decode_rejects_non_encode".
    Perhaps you forgot some 'llvm_var' statements in your spec?